#!/bin/bash

# git show $(git log --pretty=oneline|fzf --prompt='open>' --preview 'git show {1}' --select-1 --exit-0|awk '{print $1}')

git log --pretty=oneline \
|fzf --prompt='git show>' --preview 'git show {1}' --select-1 --exit-0 \
|awk '{print $1}' \
|xargs -o git show
