#!/bin/sh

mkdir -p ~/share/github
cd ~/share/github

git clone git@github.com:zetatez/.config.archlinux.git
git clone git@github.com:zetatez/.config.macos.git

git clone git@github.com:zetatez/suckless-dmenu.git
git clone git@github.com:zetatez/suckless-dwm.git
git clone git@github.com:zetatez/suckless-dwmblocks.git
git clone git@github.com:zetatez/suckless-sent.git
git clone git@github.com:zetatez/suckless-st.git

git clone git@github.com:zetatez/.password-store.git
git clone git@github.com:zetatez/lazy.git
git clone git@github.com:zetatez/hhkb.git

git clone git@github.com:zetatez/wiki.git
git clone git@github.com:zetatez/test.git
git clone git@github.com:zetatez/personal.git
git clone git@github.com:zetatez/privacy.git
git clone git@github.com:zetatez/latex-templates.git
git clone git@github.com:zetatez/photographer.git

git clone git@github.com:zetatez/HappyHacking.git
git clone git@github.com:zetatez/ECNU-L0-minimization.git
git clone git@github.com:zetatez/ECNU-compressed-sensing-research.git
git clone git@github.com:zetatez/ECNU-master-dissertation-debate.git
git clone git@github.com:zetatez/ECNU-master-dissertation.git
git clone git@github.com:zetatez/USST-dissertation.git

git clone git@github.com:zetatez/evolving.git
git clone git@github.com:zetatez/sharpe-ratio.git
git clone git@github.com:zetatez/focus-window.git
git clone git@github.com:zetatez/fancy.git
