#!/bin/sh

mkdir -p ~/github/
cd ~/github/

git clone git@gitub.com:zetatez/.config.git &
git clone git@gitub.com:zetatez/.password-store.git &
git clone git@gitub.com:zetatez/awesome-c.git &
git clone git@gitub.com:zetatez/awesome-cpp.git &
git clone git@gitub.com:zetatez/awesome-go.git &
git clone git@gitub.com:zetatez/cli.git &
git clone git@gitub.com:zetatez/cs_research.git &
git clone git@gitub.com:zetatez/debate.git &
git clone git@gitub.com:zetatez/dft.git &
git clone git@gitub.com:zetatez/diary.git &
git clone git@gitub.com:zetatez/dissertation.git &
git clone git@gitub.com:zetatez/dist-sys-reliability.git &
git clone git@gitub.com:zetatez/dotfiles.git &
git clone git@gitub.com:zetatez/evolving.git &
git clone git@gitub.com:zetatez/exam.git &
git clone git@gitub.com:zetatez/fancy.git &
git clone git@gitub.com:zetatez/HappyHacking.git &
git clone git@gitub.com:zetatez/hhkb.git &
git clone git@gitub.com:zetatez/L0-minimization.git &
git clone git@gitub.com:zetatez/latex-templates.git &
git clone git@gitub.com:zetatez/lazy.git &
git clone git@gitub.com:zetatez/lut.git &
git clone git@gitub.com:zetatez/my-play.git &
git clone git@gitub.com:zetatez/ob-ce-drm.git &
git clone git@gitub.com:zetatez/obsidian.git &
git clone git@gitub.com:zetatez/pointers-on-c.git &
git clone git@gitub.com:zetatez/privacy.git &
git clone git@gitub.com:zetatez/private.git &
git clone git@gitub.com:zetatez/self-healing.git &
git clone git@gitub.com:zetatez/self-healing-frontend.git &
git clone git@gitub.com:zetatez/sfagent.git &
git clone git@gitub.com:zetatez/sfagent-mgr.git &
git clone git@gitub.com:zetatez/slide-system-reliability.git &
git clone git@gitub.com:zetatez/slides.git &
git clone git@gitub.com:zetatez/sony-crsdk.git &
git clone git@gitub.com:zetatez/suckless-dmenu.git &
git clone git@gitub.com:zetatez/suckless-dwm.git &
git clone git@gitub.com:zetatez/suckless-dwmblocks.git &
git clone git@gitub.com:zetatez/suckless-sent.git &
git clone git@gitub.com:zetatez/suckless-st.git &
git clone git@gitub.com:zetatez/vip.git &
git clone git@gitub.com:zetatez/zsh-vi-mode.git &
