#!/bin/bash

notify-send 'reset sys default'

# ---------------------
sudo light -S 92
notify-send 'set light to 92%'

# ---------------------
amixer --card=1 set Master    unmute
amixer --card=1 set Speaker   unmute
amixer --card=1 set Capture   cap
amixer --card=1 set Master    94%
amixer --card=1 set Speaker   48%
amixer --card=1 set Capture   48%
amixer --card=1 set Headphone 48%

amixer set Master    unmute
amixer set Speaker   unmute
amixer set Capture   cap    # cap, nocap
amixer set Master    94%
amixer set Speaker   48%
amixer set Capture   48%
amixer set Headphone 48%

notify-send 'set master    volume to 92%'
notify-send 'set speaker   volume to 48%'
notify-send 'set capture   volume to 48%'
notify-send 'set headphone volume to 48%'

# ---------------------
xset r rate 158 128
notify-send 'set keyboard rate to 158 128'
