#!/bin/bash

notify-send 'reset sys default'

# ---------------------
sudo light -S 92
notify-send 'set light to 92%'

# ---------------------
# 设置音量和麦克风: 假设主音量在 card 0，麦克风在 card 1，如果不确定可用 `amixer scontrols` 查看
amixer set Master    unmute
amixer set Speaker   unmute
amixer set Capture   cap    # cap, nocap

amixer set Master    80%
amixer set Capture   64%
amixer set Speaker   64%
amixer set Headphone 64%

notify-send 'set master    volume to 80%'
notify-send 'set capture   volume to 72%'
notify-send 'set speaker   volume to 72%'
notify-send 'set headphone volume to 64%'

# ---------------------
xset r rate 158 128
notify-send 'set keyboard rate to 158 128'
