#!/usr/bin/env zsh

st -e zsh -lc '
dir=$(
  {
    echo "$HOME/.config"
    fd -t d . "$HOME/share/github"
  } | fzf --prompt="where to open lazygit>" --height 40% --reverse --preview "ls -lah {}"
)

if [[ -n "$dir" ]]; then
  cd "$dir"
fi

lazygit

exec zsh -i
'
