app:
  name: assistant
  host: 0.0.0.0
  port: 4321
  root_username: admin
  root_password: AAaa00__

log:
  level: debug
  filename: ~/.config/assistant/logs/assistant.log
  max_size_mb: 8
  max_backups: 7
  max_age_days: 7
  compress: true
  format: text
  console: true

settings:
  vpn: "socks5://127.0.0.1:7891"
  default_monitor: "eDP-1"
  default_terminal: "st"
  dir_snip: "~/git/obsidian/.snippets"
  dir_wallpaper: "~/Pictures/wallpapers"
  dir_working_logbook: "~/git/working/logbook"
  path_keyboard_brightness: "/sys/class/leds/tpacpi::kbd_backlight/brightness"
  path_ssh_secret: "~/.ssh/my.ssh.json"
  feishu:
    app_id: "${FEISHU_APP_ID}"
    app_secret: "${FEISHU_APP_SECRET}"
    chat_id: "${FEISHU_CHAT_ID}"

llm_proxy:
  proxied_model: "assistant"
  proxied_api_key: "sk-your-token-here"
  probe_interval: 30
  timeout: 300
  temperature: 0.3
  providers:
    - name: google
      base_url: https://generativelanguage.googleapis.com/v1beta/openai
      api_key: "${GEMINI_API_KEY}"
      models:
        - gemini-3.5-flash
      plan_type: fixed
      need_vpn: true
    - name: ark
      base_url: https://ark.cn-beijing.volces.com/api/plan/v3
      api_key: "${ARK_AGENT_PLAN_API_KEY_ZIWEI}"
      models:
        - glm-5.2
        - deepseek-v4-pro
      plan_type: fixed
      need_vpn: false
    - name: ark
      base_url: https://ark.cn-beijing.volces.com/api/plan/v3
      api_key: "${ARK_AGENT_PLAN_API_KEY}"
      models:
        - glm-5.2
        - deepseek-v4-pro
      plan_type: fixed
      need_vpn: false
    - name: deepseek
      base_url: https://api.deepseek.com
      api_key: "${DEEPSEEK_API_KEY}"
      models:
        - deepseek-v4-pro
        - deepseek-v4-flash
      plan_type: payg
      need_vpn: false
    # - name: ark
    #   base_url: https://ark.cn-beijing.volces.com/api/coding/v3
    #   api_key: "${ARK_CODING_PLAN_API_KEY}"
    #   models:
    #     - glm-5.2
    #     - deepseek-v4-pro
    #   plan_type: fixed
    #   need_vpn: false

background:
  enabled: true
  procs:
    - name: dwmblocks
      command: dwmblocks
      precursor: dwm
    - name: fcitx5
      command: fcitx5 -d
      precursor: dwm
    - name: picom
      command: picom --config ~/.config/picom/picom.conf
      precursor: dwm
    - name: hhkb
      command: hhkb
      precursor: dwm
    - name: xset
      command: xset r rate 158 128
      precursor: dwm
    - name: clipmenud
      command: clipmenud
      precursor: dwm
    - name: dunst
      command: dunst
      precursor: dwm

filebrowser:
  root: "/home/shiyi"
  allow:
    - "Documents"
    - "Downloads"
    - "Music"
    - "Pictures"
    - "Videos"
    - "git"
    - "x"
    - ".config"
  deny:
    - ".ssh"
    - ".gnupg"
  public:
    - "x"
