#!/bin/bash

if [ $# -ne 1 ]; then
  echo "usage: launch.sh <command>"
  exit 1
fi

curl -s -X POST http://127.0.0.1:4321/api/svr/launch \
  -u "admin:AAaa00__" \
  -H "Content-Type: application/json" \
  -d @- <<ENDJSON
{
  "command": "$1"
}
ENDJSON
