#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "wrong param, expected exact 1 param"
  exit 1
fi

dir=$1

fd \
  --type f \
  --extension jpg \
  --extension jpeg \
  --extension png \
  --extension gif \
  --extension bmp \
  --extension tiff \
  --extension avi \
  --extension flac \
  --extension mkv \
  --extension mp3 \
  --extension mp4 \
  --hidden \
  --exclude .git \
  --exclude .cache \
  --exclude .local \
  . "$dir" \
|fzf \
  --prompt="search media of dir $dir>" \
  --preview "lazy -o view -f {}" \
  --select-1 \
  --exit-0 \
  --print0 \
|xargs -0 -o lazy -o open -f
