#!/bin/bash

URLs=(
  # "https://platform.minimaxi.com/subscribe/token-plan"
  "https://platform.deepseek.com/usage"
  "https://www.volcengine.com/activity/agentplan"
  # "https://www.volcengine.com/activity/codingplan"
  "https://console.volcengine.com/ark/region:cn-beijing/subscription/coding-plan"
  "https://console.volcengine.com/ark/region:cn-beijing/subscription/agent-plan"
)

for url in ${URLs[@]}; do
  curl -s -X POST http://127.0.0.1:4321/api/svr/open-url \
    -u "admin:AAaa00__" \
    -H "Content-Type: application/json" \
    -d @- <<ENDJSON
{
  "browser": "chrome",
  "url": "$url"
}
ENDJSON
done

