#!/bin/bash

if [ $# -ne 1 ]; then
  echo "usage: open-url-qutebrowser.sh <url>"
  exit 1
fi

curl -s -X POST http://127.0.0.1:4321/api/svr/open-url \
  -u "admin:AAaa00__" \
  -H "Content-Type: application/json" \
  -d @- <<ENDJSON
{
  "browser": "qutebrowser",
  "url": "$1"
}
ENDJSON
