#!/bin/bash

curl -s -X POST http://127.0.0.1:4321/api/svr/search-videos-online \
  -u "admin:AAaa00__" \
  -H "Content-Type: application/json" \
  -d @- <<ENDJSON
{
  "query": "go tutorial"
}
ENDJSON
