#!/bin/bash
if [ $# -gt 1 ]; then
  echo "usage: snip-create [name]"
  exit 1
fi

URL="http://127.0.0.1:4321/api/svr/snip-create"
if [ -n "$1" ]; then
  URL="$URL?name=$1"
fi

curl -s -X POST "$URL" \
  -u "admin:AAaa00__"
