#!/bin/bash
if [ $# -ne 2 ]; then
  echo "usage: toggle <process> <match>"
  exit 1
fi

curl -s -X POST http://127.0.0.1:4321/api/svr/toggle \
  -u "admin:AAaa00__" \
  -H "Content-Type: application/json" \
  -d @- <<ENDJSON
{
  "process": "$1",
  "match": "$2"
}
ENDJSON
