#!/bin/bash
if [ $# -ne 1 ]; then
  echo "usage: toggle.sh <process>"
  exit 1
fi

curl -s -X POST http://127.0.0.1:4321/api/svr/toggle \
  -u "admin:AAaa00__" \
  -H "Content-Type: application/json" \
  -d "{\"process\":\"$1\"}"
