#!/bin/bash

INITIAL_QUERY=""
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"

matched=$(\
  FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf \
  --prompt='search file content> ' \
  --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
  --bind "change:reload:$RG_PREFIX {q} || true" \
  --ansi \
  --disabled \
  --query "$INITIAL_QUERY" \
  --height=100% \
  --layout=reverse \
  --delimiter : \
)

filepath=$(echo $matched|awk -F: '{print $1}')
rowno=$(echo $matched|awk -F: '{print $2}')

if [ "$filepath" != "" ]; then
  nvim +$rowno $filepath;
fi
