#!/bin/bash

fd \
  --type f \
  --extension pdf \
  --extension epub \
  --extension djvu \
  --extension mobi \
  --exclude .git \
  --exclude .cache \
  --exclude .local \
  --hidden \
  . "$HOME" \
|fzf \
  --prompt='search book>' \
  --preview 'lazy -o view -f {}' \
  --select-1 \
  --exit-0 \
  --print0 \
|xargs -0 -o lazy -o open -f
