#!/bin/sh

# ---------------------
sudo light -S 92
notify-send 'set light to 92%'

# ---------------------
amixer --card=1 set Master  unmute
amixer --card=1 set Speaker unmute
amixer --card=1 set Capture cap    # cap, nocap
amixer --card=1 set Master    94%
amixer --card=1 set Speaker   88%
amixer --card=1 set Capture   88%
amixer --card=1 set Headphone 88% # 耳机

amixer set Master    unmute
amixer set Speaker   unmute
amixer set Capture   cap    # cap, nocap
amixer set Master    94%
amixer set Speaker   88%
amixer set Capture   88%
amixer set Headphone 88% # 耳机

notify-send 'set master    volume to 92%'
notify-send 'set speaker   volume to 88%'
notify-send 'set capture   volume to 88%'
notify-send 'set headphone volume to 88%'

# ---------------------
xset r rate 158 128
notify-send 'set keyboard rate to 158 128'
