#!/usr/bin/env bash

notify-send 'reset sys default'

# ---------------------
sudo light -S 48
notify-send 'set light to 92%'

# ---------------------
# set volume and microphone
amixer set Master    unmute
amixer set Speaker   unmute
amixer set Capture   cap    # cap, nocap

amixer set Master    80%
amixer set Capture   64%
amixer set Speaker   64%
amixer set Headphone 64%

notify-send 'set master    volume to 80%'
notify-send 'set capture   volume to 72%'
notify-send 'set speaker   volume to 72%'
notify-send 'set headphone volume to 64%'

# ---------------------
xset r rate 158 128
notify-send 'set keyboard rate to 158 128'
